name: massa sc ci tests
on: [push]
jobs:
  sc-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
        working-directory: ./smart-contract

      - name: Install
        run: npm ci
        working-directory: ./smart-contract

      - name: Test
        run: npm run test
        working-directory: ./smart-contract

