name: massa sc ci tests
on: [push]
jobs:
  sc-unit-tests:
    defaults:
      run:
        working-directory: ./smart-contract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test
